apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat-deployment-app
  labels:
    app: tomcat
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tomcat
  template:
    metadata:
      labels:
        app: tomcat
      containers:
      - name: tomcat
        image: durga2411/cicddevops:25
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: tomcat-deployment
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: tomcat
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30007
...


        
